# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 269)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(50, 25))
        self.label.setMaximumSize(QtCore.QSize(50, 25))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.account_led = QtWidgets.QLineEdit(Form)
        self.account_led.setObjectName("account_led")
        self.horizontalLayout.addWidget(self.account_led)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(50, 25))
        self.label_2.setMaximumSize(QtCore.QSize(50, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.psw_led = QtWidgets.QLineEdit(Form)
        self.psw_led.setEchoMode(QtWidgets.QLineEdit.Password)
        self.psw_led.setObjectName("psw_led")
        self.horizontalLayout_2.addWidget(self.psw_led)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.yzm_led = QtWidgets.QLineEdit(Form)
        self.yzm_led.setObjectName("yzm_led")
        self.horizontalLayout_3.addWidget(self.yzm_led)
        self.yzm_label = QtWidgets.QLabel(Form)
        self.yzm_label.setObjectName("yzm_label")
        self.horizontalLayout_3.addWidget(self.yzm_label)
        self.replace_btn = QtWidgets.QPushButton(Form)
        self.replace_btn.setObjectName("replace_btn")
        self.horizontalLayout_3.addWidget(self.replace_btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setEnabled(False)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.login_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_4.addWidget(self.login_btn)
        self.again_btn = QtWidgets.QPushButton(Form)
        self.again_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.again_btn.setObjectName("again_btn")
        self.horizontalLayout_4.addWidget(self.again_btn)
        self.recover_pass_btn = QtWidgets.QPushButton(Form)
        self.recover_pass_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.recover_pass_btn.setObjectName("recover_pass_btn")
        self.horizontalLayout_4.addWidget(self.recover_pass_btn)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)

        self.retranslateUi(Form)
        self.login_btn.clicked.connect(Form.check_login)
        self.replace_btn.clicked.connect(Form.replace_yzm)
        self.again_btn.clicked.connect(Form.Reset_info)
        self.recover_pass_btn.clicked.connect(Form.recover_pwd)
        self.account_led.textChanged['QString'].connect(Form.Led_is_text)
        self.psw_led.textChanged['QString'].connect(Form.Led_is_text)
        self.yzm_led.textChanged['QString'].connect(Form.Led_is_text)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "聊城大学教务系统"))
        self.label.setText(_translate("Form", "账号:"))
        self.account_led.setText(_translate("Form", "2017205815"))
        self.label_2.setText(_translate("Form", "密码:"))
        self.psw_led.setText(_translate("Form", "a06051316"))
        self.label_3.setText(_translate("Form", "验证码:"))
        self.yzm_label.setText(_translate("Form", "TextLabel"))
        self.replace_btn.setText(_translate("Form", "换一张"))
        self.login_btn.setText(_translate("Form", "登录"))
        self.again_btn.setText(_translate("Form", "重设"))
        self.recover_pass_btn.setText(_translate("Form", "密码找回"))

