# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainingprogram.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 767)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 301, 741))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setGeometry(QtCore.QRect(10, 20, 281, 711))
        self.treeWidget.setObjectName("treeWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 10, 741, 521))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 30, 131, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_3.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_3.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_31.setFont(font)
        self.label_31.setText("")
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_32.setFont(font)
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_33.setFont(font)
        self.label_33.setText("")
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_3.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_34.setFont(font)
        self.label_34.setText("")
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_3.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_3.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_36.setFont(font)
        self.label_36.setText("")
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_3.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_37.setFont(font)
        self.label_37.setText("")
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_3.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_38.setFont(font)
        self.label_38.setText("")
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_3.addWidget(self.label_38)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(510, 30, 211, 471))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.coursename = QtWidgets.QLabel(self.layoutWidget_2)
        self.coursename.setText("")
        self.coursename.setObjectName("coursename")
        self.verticalLayout_4.addWidget(self.coursename)
        self.Coursedepartment = QtWidgets.QLabel(self.layoutWidget_2)
        self.Coursedepartment.setText("")
        self.Coursedepartment.setObjectName("Coursedepartment")
        self.verticalLayout_4.addWidget(self.Coursedepartment)
        self.Researchlogo = QtWidgets.QLabel(self.layoutWidget_2)
        self.Researchlogo.setText("")
        self.Researchlogo.setObjectName("Researchlogo")
        self.verticalLayout_4.addWidget(self.Researchlogo)
        self.Classhour = QtWidgets.QLabel(self.layoutWidget_2)
        self.Classhour.setText("")
        self.Classhour.setObjectName("Classhour")
        self.verticalLayout_4.addWidget(self.Classhour)
        self.Enddate = QtWidgets.QLabel(self.layoutWidget_2)
        self.Enddate.setText("")
        self.Enddate.setObjectName("Enddate")
        self.verticalLayout_4.addWidget(self.Enddate)
        self.Inclassweektime = QtWidgets.QLabel(self.layoutWidget_2)
        self.Inclassweektime.setText("")
        self.Inclassweektime.setObjectName("Inclassweektime")
        self.verticalLayout_4.addWidget(self.Inclassweektime)
        self.Designtotalhours = QtWidgets.QLabel(self.layoutWidget_2)
        self.Designtotalhours.setText("")
        self.Designtotalhours.setObjectName("Designtotalhours")
        self.verticalLayout_4.addWidget(self.Designtotalhours)
        self.Midtermtotalcomputerhours = QtWidgets.QLabel(self.layoutWidget_2)
        self.Midtermtotalcomputerhours.setText("")
        self.Midtermtotalcomputerhours.setObjectName("Midtermtotalcomputerhours")
        self.verticalLayout_4.addWidget(self.Midtermtotalcomputerhours)
        self.Designassignmenttotalhours = QtWidgets.QLabel(self.layoutWidget_2)
        self.Designassignmenttotalhours.setText("")
        self.Designassignmenttotalhours.setObjectName("Designassignmenttotalhours")
        self.verticalLayout_4.addWidget(self.Designassignmenttotalhours)
        self.Extracurricularcredits = QtWidgets.QLabel(self.layoutWidget_2)
        self.Extracurricularcredits.setText("")
        self.Extracurricularcredits.setObjectName("Extracurricularcredits")
        self.verticalLayout_4.addWidget(self.Extracurricularcredits)
        self.teachingmethods = QtWidgets.QLabel(self.layoutWidget_2)
        self.teachingmethods.setText("")
        self.teachingmethods.setObjectName("teachingmethods")
        self.verticalLayout_4.addWidget(self.teachingmethods)
        self.teachnumber_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.teachnumber_2.setText("")
        self.teachnumber_2.setObjectName("teachnumber_2")
        self.verticalLayout_4.addWidget(self.teachnumber_2)
        self.teachingmaterial_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.teachingmaterial_2.setText("")
        self.teachingmaterial_2.setObjectName("teachingmaterial_2")
        self.verticalLayout_4.addWidget(self.teachingmaterial_2)
        self.referencebook_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.referencebook_2.setText("")
        self.referencebook_2.setObjectName("referencebook_2")
        self.verticalLayout_4.addWidget(self.referencebook_2)
        self.Faculty_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.Faculty_2.setText("")
        self.Faculty_2.setObjectName("Faculty_2")
        self.verticalLayout_4.addWidget(self.Faculty_2)
        self.Testtype = QtWidgets.QLabel(self.layoutWidget_2)
        self.Testtype.setText("")
        self.Testtype.setObjectName("Testtype")
        self.verticalLayout_4.addWidget(self.Testtype)
        self.Campus_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.Campus_2.setText("")
        self.Campus_2.setObjectName("Campus_2")
        self.verticalLayout_4.addWidget(self.Campus_2)
        self.briefintroduction_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.briefintroduction_2.setText("")
        self.briefintroduction_2.setObjectName("briefintroduction_2")
        self.verticalLayout_4.addWidget(self.briefintroduction_2)
        self.Remarks_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.Remarks_2.setText("")
        self.Remarks_2.setObjectName("Remarks_2")
        self.verticalLayout_4.addWidget(self.Remarks_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 32, 131, 471))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(150, 30, 211, 471))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.coursenumber = QtWidgets.QLabel(self.layoutWidget2)
        self.coursenumber.setText("")
        self.coursenumber.setObjectName("coursenumber")
        self.verticalLayout_2.addWidget(self.coursenumber)
        self.englishcoursename = QtWidgets.QLabel(self.layoutWidget2)
        self.englishcoursename.setText("")
        self.englishcoursename.setObjectName("englishcoursename")
        self.verticalLayout_2.addWidget(self.englishcoursename)
        self.Semester = QtWidgets.QLabel(self.layoutWidget2)
        self.Semester.setText("")
        self.Semester.setObjectName("Semester")
        self.verticalLayout_2.addWidget(self.Semester)
        self.credit = QtWidgets.QLabel(self.layoutWidget2)
        self.credit.setText("")
        self.credit.setObjectName("credit")
        self.verticalLayout_2.addWidget(self.credit)
        self.Startdata = QtWidgets.QLabel(self.layoutWidget2)
        self.Startdata.setText("")
        self.Startdata.setObjectName("Startdata")
        self.verticalLayout_2.addWidget(self.Startdata)
        self.coursestatus = QtWidgets.QLabel(self.layoutWidget2)
        self.coursestatus.setText("")
        self.coursestatus.setObjectName("coursestatus")
        self.verticalLayout_2.addWidget(self.coursestatus)
        self.Totalclasshours = QtWidgets.QLabel(self.layoutWidget2)
        self.Totalclasshours.setText("")
        self.Totalclasshours.setObjectName("Totalclasshours")
        self.verticalLayout_2.addWidget(self.Totalclasshours)
        self.Experimentaltotalhours = QtWidgets.QLabel(self.layoutWidget2)
        self.Experimentaltotalhours.setText("")
        self.Experimentaltotalhours.setObjectName("Experimentaltotalhours")
        self.verticalLayout_2.addWidget(self.Experimentaltotalhours)
        self.Discussioncounselingtotalhours = QtWidgets.QLabel(self.layoutWidget2)
        self.Discussioncounselingtotalhours.setText("")
        self.Discussioncounselingtotalhours.setObjectName("Discussioncounselingtotalhours")
        self.verticalLayout_2.addWidget(self.Discussioncounselingtotalhours)
        self.Extracurriculartotalhours = QtWidgets.QLabel(self.layoutWidget2)
        self.Extracurriculartotalhours.setText("")
        self.Extracurriculartotalhours.setObjectName("Extracurriculartotalhours")
        self.verticalLayout_2.addWidget(self.Extracurriculartotalhours)
        self.cousertype = QtWidgets.QLabel(self.layoutWidget2)
        self.cousertype.setText("")
        self.cousertype.setObjectName("cousertype")
        self.verticalLayout_2.addWidget(self.cousertype)
        self.teachnumber = QtWidgets.QLabel(self.layoutWidget2)
        self.teachnumber.setText("")
        self.teachnumber.setObjectName("teachnumber")
        self.verticalLayout_2.addWidget(self.teachnumber)
        self.teachingmaterial = QtWidgets.QLabel(self.layoutWidget2)
        self.teachingmaterial.setText("")
        self.teachingmaterial.setObjectName("teachingmaterial")
        self.verticalLayout_2.addWidget(self.teachingmaterial)
        self.referencebook = QtWidgets.QLabel(self.layoutWidget2)
        self.referencebook.setText("")
        self.referencebook.setObjectName("referencebook")
        self.verticalLayout_2.addWidget(self.referencebook)
        self.Faculty = QtWidgets.QLabel(self.layoutWidget2)
        self.Faculty.setText("")
        self.Faculty.setObjectName("Faculty")
        self.verticalLayout_2.addWidget(self.Faculty)
        self.Coursedescription = QtWidgets.QLabel(self.layoutWidget2)
        self.Coursedescription.setText("")
        self.Coursedescription.setObjectName("Coursedescription")
        self.verticalLayout_2.addWidget(self.Coursedescription)
        self.Campus = QtWidgets.QLabel(self.layoutWidget2)
        self.Campus.setText("")
        self.Campus.setObjectName("Campus")
        self.verticalLayout_2.addWidget(self.Campus)
        self.briefintroduction = QtWidgets.QLabel(self.layoutWidget2)
        self.briefintroduction.setText("")
        self.briefintroduction.setObjectName("briefintroduction")
        self.verticalLayout_2.addWidget(self.briefintroduction)
        self.Remarks = QtWidgets.QLabel(self.layoutWidget2)
        self.Remarks.setText("")
        self.Remarks.setObjectName("Remarks")
        self.verticalLayout_2.addWidget(self.Remarks)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 540, 741, 211))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(149, 30, 221, 171))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Plannedschoolyear = QtWidgets.QLabel(self.layoutWidget_3)
        self.Plannedschoolyear.setText("")
        self.Plannedschoolyear.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Plannedschoolyear.setObjectName("Plannedschoolyear")
        self.verticalLayout_6.addWidget(self.Plannedschoolyear)
        self.Courseattribute = QtWidgets.QLabel(self.layoutWidget_3)
        self.Courseattribute.setText("")
        self.Courseattribute.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Courseattribute.setObjectName("Courseattribute")
        self.verticalLayout_6.addWidget(self.Courseattribute)
        self.Remarks1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.Remarks1.setText("")
        self.Remarks1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Remarks1.setObjectName("Remarks1")
        self.verticalLayout_6.addWidget(self.Remarks1)
        self.Remarks2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.Remarks2.setText("")
        self.Remarks2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Remarks2.setObjectName("Remarks2")
        self.verticalLayout_6.addWidget(self.Remarks2)
        self.Remarks3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.Remarks3.setText("")
        self.Remarks3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Remarks3.setObjectName("Remarks3")
        self.verticalLayout_6.addWidget(self.Remarks3)
        self.Remarks4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.Remarks4.setText("")
        self.Remarks4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Remarks4.setObjectName("Remarks4")
        self.verticalLayout_6.addWidget(self.Remarks4)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 30, 101, 171))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_5.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_5.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_5.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_5.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_5.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_5.addWidget(self.label_44)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(380, 30, 141, 51))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_7.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_7.addWidget(self.label_46)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(530, 30, 191, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Plansemester = QtWidgets.QLabel(self.layoutWidget5)
        self.Plansemester.setText("")
        self.Plansemester.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Plansemester.setObjectName("Plansemester")
        self.verticalLayout_8.addWidget(self.Plansemester)
        self.Testtype2 = QtWidgets.QLabel(self.layoutWidget5)
        self.Testtype2.setText("")
        self.Testtype2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Testtype2.setObjectName("Testtype2")
        self.verticalLayout_8.addWidget(self.Testtype2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "课组查询"))
        self.groupBox_2.setTitle(_translate("Form", "方案计划信息"))
        self.label_20.setText(_translate("Form", "课程名"))
        self.label_21.setText(_translate("Form", "开课系所"))
        self.label_22.setText(_translate("Form", "本研标志"))
        self.label_23.setText(_translate("Form", "学时"))
        self.label_24.setText(_translate("Form", "结束日期"))
        self.label_25.setText(_translate("Form", "课内周学时"))
        self.label_26.setText(_translate("Form", "设计总学时"))
        self.label_27.setText(_translate("Form", "其中上机总学时"))
        self.label_28.setText(_translate("Form", "设计作业总学时"))
        self.label_29.setText(_translate("Form", "课外学分"))
        self.label_30.setText(_translate("Form", "教学方式"))
        self.label_35.setText(_translate("Form", "考试类型"))
        self.label.setText(_translate("Form", "课程号"))
        self.label_2.setText(_translate("Form", "英文课程名"))
        self.label_3.setText(_translate("Form", "开课学期"))
        self.label_4.setText(_translate("Form", "学分"))
        self.label_5.setText(_translate("Form", "开始设立日期"))
        self.label_6.setText(_translate("Form", "课程状态"))
        self.label_7.setText(_translate("Form", "授课总学时"))
        self.label_8.setText(_translate("Form", "实验总学时"))
        self.label_9.setText(_translate("Form", "讨论辅导总学时"))
        self.label_10.setText(_translate("Form", "课外总学时"))
        self.label_11.setText(_translate("Form", "课程类别"))
        self.label_12.setText(_translate("Form", "教师号"))
        self.label_13.setText(_translate("Form", "教材"))
        self.label_14.setText(_translate("Form", "参考书"))
        self.label_16.setText(_translate("Form", "师资队伍"))
        self.label_15.setText(_translate("Form", "课程说明"))
        self.label_17.setText(_translate("Form", "校区"))
        self.label_18.setText(_translate("Form", "内容简介"))
        self.label_19.setText(_translate("Form", "备注"))
        self.groupBox_3.setTitle(_translate("Form", "方案课程信息"))
        self.label_39.setText(_translate("Form", "计划学年"))
        self.label_40.setText(_translate("Form", "课程属性"))
        self.label_41.setText(_translate("Form", "备注1"))
        self.label_42.setText(_translate("Form", "备注2"))
        self.label_43.setText(_translate("Form", "备注3"))
        self.label_44.setText(_translate("Form", "备注4"))
        self.label_45.setText(_translate("Form", "计划学期"))
        self.label_46.setText(_translate("Form", "考试类型"))

